### ISSUE TITLE
Dev scanner doesn't work as expected

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#33]
@JesusGarcia98 I am experimenting the dev scanning and I am a bit surprise by the outcome.

With all the change made I am afraid we lost some key initial feature.

For instance I have some tags that are not recognized anymore or just with a specific rotation 

did you change anything about rotation?

Here is for instance what I get with the master branch

![screen shot 2019-02-25 at 10 15 19 am](https://user-images.githubusercontent.com/3928502/53364756-7f067b00-390d-11e9-825a-d6d8963ead7e.png)

and what I have with the dev, many tags are not recognize 

![screen shot 2019-02-25 at 2 55 23 pm](https://user-images.githubusercontent.com/3928502/53364783-90e81e00-390d-11e9-9bef-5a3d2d934b79.png)

**Comment by JesusGarcia98** [comment]
What do you mean with they are not recognized anymore? They do not get assigned the correct pattern id when they are rotated?

**Comment by agrignard** [comment]
Yes but not for all of them. For instance the one of the very right (red,white,white, black) is only recognize for one type of rotation and not for the 3 other one

**Comment by JesusGarcia98** [comment]
Found the issue. When creating the color patterns I used a certain order for the colors, but the comparisons for each rotation was using another order, which is why some patterns were not recognized properly. With the commit I made, it should be working.

**Comment by agrignard** [comment]
ok so its getting better hozever it seems that there is still a problem.  in this picture the !st and the $st (starting from the left side of the picture are not recongnized.
![screen shot 2019-02-26 at 3 54 35 pm](https://user-images.githubusercontent.com/3928502/53445656-07088580-39df-11e9-8ef4-c46bcaec7805.png)

**Comment by JesusGarcia98** [comment]
I tried replicating the setup shown in the pictures, and in my case it does detect the patterns correctly.
<img width="418" alt="captura de pantalla 2019-02-27 a la s 14 31 06" src="https://user-images.githubusercontent.com/39389243/53517447-99bb2a00-3a9c-11e9-9519-924037076a9d.png">

**Comment by agrignard** [comment]
I am still not able to make it work for id =0 and id = 4. 

Did you push everything from your local version? What about your calibration parameters? We migt have a different settings in term of light

Also how do you display the final results as you did in the last picture?

**Comment by JesusGarcia98** [comment]
Yes, I am sure I pushed the fix for the order in the patterns. I now have pushed the calibration parameters I used to properly recognize id=0 and id=4.
